### ISSUE TITLE
(Suggestion) Grizzly Bears should attack wild Wolves

### ISSUE THREAD

**Issue by Brun333rp** [AlexModGuy/AlexsMobs#127]
If not outnumbered, Wolves should attack them as well. However, they would always attack baby Grizzly Bears if these are alone, regardles of numbers.

**Comment by Robongio** [comment]
#367 should potentially get this case closed.

**Comment by Brun333rp** [comment]
that's good! I thought that it would be forgotten forever

**Comment by Robongio** [comment]
Just remember next time to give any suggestions somewhere else. Instead of reporting it as an actual issue.
