### ISSUE TITLE
Client crash Quark 1.18.2 + Alex Mobs 1.18.6

### ISSUE THREAD

**Issue by XionioXMaster** [AlexModGuy/AlexsMobs#1319]
The client of nearby players can be disabled using the Quark animation in the "T" menu while abruptly using Rocky Carapace

https://mcpaste.com/05eeb0e30ca74e8f68d735021a3423d3

**Comment by GitJhopa** [comment]
[crash-2022-09-09_20.23.13-client.txt](https://github.com/AlexModGuy/AlexsMobs/files/9537589/crash-2022-09-09_20.23.13-client.txt)
 
 Too problem in 1.19.2 Forge.
