### ISSUE TITLE
1.19.2 shaders problem with Underminder

### ISSUE THREAD

**Issue by AlienLoser** [AlexModGuy/AlexsMobs#1404]
To make it simple, anytime an underminer mines something underground, and you have shaders (doesnt matter what kind), it makes everything kind of invisible? as seen below by me and my friend. We both have different shaders. BSL and Astralex in order of photo. This is kind of annoying, maybe a little game breaking as we can see everything as if we're in spectator mode, but something to fix nonetheless.
![image](https://user-images.githubusercontent.com/117137863/199154605-6f72d07e-1b6c-4793-bb7f-31e2615ebf84.png)
![image](https://user-images.githubusercontent.com/117137863/199154650-4f9bbc41-9c45-45d2-a259-257e7bd1e93e.png)

**Comment by arrowdannad** [comment]
我也遇到了同样的问题
I had the same problem
