### ISSUE TITLE
Frozen Dead Sunbird

### ISSUE THREAD

**Issue by Rizco0** [AlexModGuy/AlexsMobs#176]
"Killing" the sunbird causes it to stay stuck forever. Not sure if it is actually dead due to health being stuck at 3.5
![image](https://user-images.githubusercontent.com/78776702/107315763-52e65500-6a65-11eb-91e4-86472675d1f0.png)

**Comment by mcquestion** [comment]
Tried to reproduce this on the latest forge version and mod version, sunbird reliably died every time for me, this may be fixed now?
