### ISSUE TITLE
Possible issue with Gorillas and their pathfinding.

### ISSUE THREAD

**Issue by ArchieBeepBoop** [AlexModGuy/AlexsMobs#180]
**Mod Version:** 1.5.0
**Forge Version:** 36.0.13
**Minecraft Version:** 1.16.5

Earlier today I had this crash on my dedicated Valhelsia 3 server where apparently a gorilla overloaded the server's ticks when trying to forage. Possibly an issue.

Here's the Github geist link for the crashlog:
https://gist.github.com/ArchieBeepBoop/969ad90e4ad33858e13b76ac384bc9d0

**Comment by Avilaaiops** [comment]
I have an almost identical stacktrace, though I'm on version 1.4.0

Bump!

**Comment by BentiGorlich** [comment]
I had the same issue just now. But I am not using the Valhelsia modpack, I am using the Direwolf Modpack with some extra mods (including ALex's Mobs)
