### ISSUE TITLE
EntityLeafcutterAnt TPS Lag

### ISSUE THREAD

**Issue by czaux** [AlexModGuy/AlexsMobs#382]
Getting severe drops in TPS as reported by Spark: https://spark.lucko.me/MPJkNwUnVE

net.minecraft.world.server.ServerWorld$$Lambda$25954/1419910971.accept()84.04%
    net.minecraft.world.server.ServerWorld.updateEntity()84.04%
        com.github.alexthe666.alexsmobs.entity.EntityLeafcutterAnt.tick()79.05%
            net.minecraft.entity.MobEntity.tick()78.39%
                net.minecraft.entity.LivingEntity.tick()78.38%
                    net.minecraft.entity.passive.AnimalEntity.livingTick()68.42%
                        net.minecraft.entity.AgeableEntity.livingTick()68.42%
                            net.minecraft.entity.MobEntity.livingTick()68.32%
                                net.minecraft.entity.LivingEntity.livingTick()68.32%
                                    net.minecraft.entity.LivingEntity.collideWithNearbyEntities()30.12%
                                    net.minecraft.entity.LivingEntity.travel()27.38%
                                        net.minecraft.entity.LivingEntity.func_233633_a_()26.35%
                                        net.minecraft.entity.Entity.move()26.22%14068ms (self: 152ms - 0.28%)

I removed Alexsmobs from mods and TPS is normal.

**Comment by Drulgaard** [comment]
I had this issue, and used `/kill @e[type=alexsmobs:leafcutter_ant]` which killed 1517 entities, and my server's TPS recovered from 10 back to 20.  I assume they multiply... perhaps that should be capped!
