### ISSUE TITLE
Problem with citadel

### ISSUE THREAD

**Issue by mcaskilSeed** [AlexModGuy/AlexsMobs#457]
How do i fix it
![image](https://user-images.githubusercontent.com/78537050/119620008-68378300-bdb9-11eb-9207-733a33a9f24d.png)

**Comment by mcaskilSeed** [comment]
I CAN'T FKN LOAD THE MOD IF YOU DIDN'T FIX THIS FKN PROBLEM

**Comment by PlummetStudios** [comment]
1. Calm down

2. This is the AM repository, not the citadel one

3. Make sure you have the latest forge version as well as latest citadel version. Delete any configs you've made already.

**Comment by mcaskilSeed** [comment]
> 1. Calm down
> 2. This is the AM repository, not the citadel one
> 3. Make sure you have the latest forge version as well as latest citadel version. Delete any configs you've made already.

ok thanks
