### ISSUE TITLE
Leafcutter anthills infinitely spawns ants

### ISSUE THREAD

**Issue by Carro1001** [AlexModGuy/AlexsMobs#839]
Like actually infinite, 100+ ants just infinitely come out of 1 nest sometimes

**Comment by AlexModGuy** [comment]
spawns as in worldgen or placed? under what conditions

**Comment by dKatsuro** [comment]
Didn't want to create a new bug report for this so I will just post this here. I came across this issue today and I haven't really done anything special it seems there is no cap on the number of leafcutter ants spawning. 

I was playing and noticed lag and running /forge tps I saw my TPS was around 5. Ran the TPS profiler and saw the following.
https://i.ibb.co/T0bsBQM/2022-03-01-03-11-39.png
https://i.ibb.co/TM4kDc6/2022-03-01-03-12-21.png
https://i.ibb.co/WDHcRVJ/2022-03-01-03-11-27.png

There are only 2 ant hills in this area and when I ran `/kill @e[type=alexsmobs:leafcutter_ant]` it killed 644 entities.

I didn't place any anthills and this is actually a new single player instance I have been playing for a few hours. So this is from regular worldgen. I don't think it took very long for it to get to this point - maybe about an hour? I recall walking by the area about an hour ago so it loaded the two anthills in and then I guess just continued to infinitely spawn the ants.

There was a single anthill next to my base and I noticed the ants were getting a bit out of control (before it got to the point in the pictures) so I killed the queen to stop the spawning.

I'm playing in the All The Mods 7 pack (version 7-0.2.45) and it is running  the current version (1.17.1) of Alex's Mobs.
 
 Upon looking around on reddit it seems this issue has been around for a while?
 https://www.reddit.com/r/feedthebeast/comments/ovmm5u/i_swear_i_set_the_colony_size_limit_to_20/
 
 Although - looking at this post it seems like some people tracked this issue down to a 'performance enhancing' mod that is supposed to help but really removes the spawn caps on some mods.
 https://www.reddit.com/r/feedthebeast/comments/msr7rf/so_many_mobs_spawning_oh_the_biomes_youll_go/

**Comment by Carro1001** [comment]
Do you have mobgriefing turned off? Trying to figure out what causes this

**Comment by dKatsuro** [comment]
No, mobGriefing is currently set to true.

**Comment by Wafool** [comment]
I actually came here to report this myself and noticed it was already open. I'm playing on the All The Mods 7 modpack in a single player world. The mod version is alexsmobs-1.17.5. I was only like 5 or 6 hours into the pack when I started noticing tons of lag. TPS was down to 9. I ran a spark profiler and turns out leafcutter ants were showing at 58% usage. So I ran the kill command on them and it cleared like 300 mobs. The problem still persisted though. Turns out the kill command only worked for ants that were outside the hive. I ended up finding the hive and did another kill command. It killed the ants that were outside of the hive but immediately, more started pouring out. So I had to destroy the hive and kill the queen. Then it all cleared up. This was all from 1 hive.

**Comment by nonchip** [comment]
mobGriefing *off* here (which by the way the ants seem to ignore and eat all the leaves anyway), and this just happened in a completely untouched piece of jungle shore:
![image](https://user-images.githubusercontent.com/601018/166148446-889f2866-cd07-43e6-88f6-5928b5cb11bb.png)

note other anthills i encountered did the same, but slower so i didn't notice outright.

`/kill @e[type=alexsmobs:leafcutter_ant]` said `726`!

while this is being worked on, is there a way of simply limiting e.g. the amount of equal entities per chunk or something? i don't want to outright disable all ants but... this is ridiculous and about to eat my world!

**EDIT**: I just wrote this CraftTweaker script, which *should* (no warranty and all that!) keep them in check:
```js
import crafttweaker.api.events.CTEventManager;
import crafttweaker.api.event.entity.EntityJoinWorldEvent;
import crafttweaker.api.event.living.LivingUpdateEvent;
import crafttweaker.api.entity.Entity;
import crafttweaker.api.util.math.BlockPos;
// Every time an Entity "joins" (spawns) the World...
CTEventManager.register<crafttweaker.api.event.entity.EntityJoinWorldEvent>((event) => {
	val level = event.world;
	var range = 64;
	var nospawnNumber = 20 as usize;
	var cullingNumber = 25 as usize;
	// If it's an Ant...
	if event.entity.getType() == <entitytype:alexsmobs:leafcutter_ant> {
		var pos1 = new BlockPos(event.entity.blockX-range, event.entity.blockY-range, event.entity.blockZ-range);
		var pos2 = new BlockPos(event.entity.blockX+range, event.entity.blockY+range, event.entity.blockZ+range);
		// Get all Ants in the 64 block range...
		var ents = level.getEntities(event.entity, pos1.x, pos1.y, pos1.z, pos2.x, pos2.y, pos2.z, e => e.getType() == <entitytype:alexsmobs:leafcutter_ant>);
		// if there are more than 20...
		if(ents.length > nospawnNumber){
			// don't allow it to "join"
			event.cancel();
		}
		// if there are more than 25...
		if(ents.length > cullingNumber){
			// kill them all
			for ent in ents {
				ent.kill();
			}
		}
	}
});
```
this should both limit their numbers, and cull every one outside the hill as soon as they're getting out of hand (or if they were still out of hand from an earlier save)

you might have to change the `range` value to adjust for performance impact vs. effectiveness (higher values require to search a larger area, lower values might miss ants if they wander too far and still keep spawning way above the target number)

**Comment by nonchip** [comment]
@Alex-the-666 by the way i did some digging and yeah......

* first you add ants to a list *if below threshold* https://github.com/Alex-the-666/AlexsMobs/blob/ee6f4ee05804bf1e19e089bff58f5c5ff70457ab/src/main/java/com/github/alexthe666/alexsmobs/tileentity/TileEntityLeafcutterAnthill.java#L182 https://github.com/Alex-the-666/AlexsMobs/blob/ee6f4ee05804bf1e19e089bff58f5c5ff70457ab/src/main/java/com/github/alexthe666/alexsmobs/tileentity/TileEntityLeafcutterAnthill.java#L194
https://github.com/Alex-the-666/AlexsMobs/blob/ee6f4ee05804bf1e19e089bff58f5c5ff70457ab/src/main/java/com/github/alexthe666/alexsmobs/tileentity/TileEntityLeafcutterAnthill.java#L197
* then you **remove them from that list** when you spawn them: https://github.com/Alex-the-666/AlexsMobs/blob/ee6f4ee05804bf1e19e089bff58f5c5ff70457ab/src/main/java/com/github/alexthe666/alexsmobs/tileentity/TileEntityLeafcutterAnthill.java#L345 https://github.com/Alex-the-666/AlexsMobs/blob/ee6f4ee05804bf1e19e089bff58f5c5ff70457ab/src/main/java/com/github/alexthe666/alexsmobs/tileentity/TileEntityLeafcutterAnthill.java#L352-L353

so as soon as an ant is spawned, it stops counting into the "colony size". you just made a world nuker.
